### ISSUE TITLE
Eukare服务端或客户端启动后一直去8761端口注册问题

### ISSUE THREAD

**Issue by erzhiqianyi** [erzhiqianyi/LeaningMicroservice#1]
如果启动Eukare服务端后，一直出现去8761端口注册，且注册失败得情况，可能是客户端配置有问题。检查```eureka.client.service-url.defaultZone``` 配置，是```defaultZone``` ，不是```default-zone```
配置参考如下
```yml
eureka:
  instance:
    hostname: 192.168.0.176
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.176:20000/eureka
```
