### ISSUE TITLE
使用CloudConfig配置无效

### ISSUE THREAD

**Issue by erzhiqianyi** [erzhiqianyi/LeaningMicroservice#3]
## 环境配置
```bootstrap.yml``` 配置如下 
```yml
spring:
  application:
    name: wechat-server
  cloud:
    # Config 客户端配置
    config:
      # 配置中心地址
      uri: http://127.0.0.1:10000
      name: wechat-server
      label: dev
```
配置文件放在 ```github```, ```Config````服务端已经启动，启动项目，没有使用 ```bootstrap.yml```  配置启动应用，而是使用默认的配置启动。
